const $=s=>document.querySelector(s);const sections=[...document.querySelectorAll('.section')];
// Access lock: before 2 June, only the exact test URL with ?test=COBRA2026 can open the experience.
const birthdayMonth=6,birthdayDay=2;const TEST_KEY='COBRA2026';const now=new Date();const birthdayStart=new Date(now.getFullYear(),birthdayMonth-1,birthdayDay);const isTest=new URLSearchParams(location.search).get('test')===TEST_KEY;const accessAllowed=now>=birthdayStart||isTest;
function lockSite(){document.body.innerHTML=`<main style="min-height:100vh;display:grid;place-items:center;padding:28px;text-align:center;font-family:Inter,Arial,sans-serif;background:#0b0b12;color:#fff"><div><div style="font-size:64px">🔒</div><h1>Birthday Surprise Locked</h1><p style="opacity:.75">This birthday experience unlocks on <b>2 June</b> 🎂</p></div></main>`;throw new Error('Birthday site locked');}
if(!accessAllowed)lockSite();
function show(id){sections.forEach(x=>x.classList.toggle('active',x.id===id));window.scrollTo({top:0,behavior:'smooth'});if(id==='letter')typeLetter();}
$('#startBtn').onclick=()=>show('intro');document.querySelectorAll('.next-btn').forEach(b=>b.onclick=()=>show(b.dataset.next));
const saved=localStorage.getItem('birthday-theme')||'dark';document.body.className=saved;$('#themeToggle').textContent=saved==='dark'?'☀️':'🌙';$('#themeToggle').onclick=()=>{const light=document.body.classList.contains('light');document.body.className=light?'dark':'light';localStorage.setItem('birthday-theme',document.body.className);$('#themeToggle').textContent=light?'☀️':'🌙';};
function tick(){const now=new Date();let target=new Date(now.getFullYear(),birthdayMonth-1,birthdayDay);if(target<now)target.setFullYear(target.getFullYear()+1);let d=target-now;const days=Math.floor(d/86400000);d%=86400000;const h=Math.floor(d/3600000);d%=3600000;const m=Math.floor(d/60000);const s=Math.floor((d%60000)/1000);$('#countdown').textContent=`${days}d ${String(h).padStart(2,'0')}h ${String(m).padStart(2,'0')}m ${String(s).padStart(2,'0')}s`;}tick();setInterval(tick,1000);
let score=0,running=false;$('#gameStart').onclick=()=>{score=0;running=true;$('#score').textContent=score;$('#gameStart').classList.add('hidden');spawn();};function spawn(){if(!running)return;const box=$('#gameBox');const heart=document.createElement('button');heart.className='heart';heart.textContent=['❤️','💖','💗','💓'][Math.floor(Math.random()*4)];heart.style.left=Math.random()*85+'%';heart.style.bottom='-50px';heart.onclick=()=>{score++;$('#score').textContent=score;heart.remove();if(score>=10){running=false;$('#gameNext').classList.remove('hidden');toast('🎉 You unlocked the secret letter!');}else spawn();};box.appendChild(heart);setTimeout(()=>{if(heart.isConnected)heart.remove();if(running)spawn();},1800);}
const letter=`Happy Birthday! 🎂\n\nI hope today reminds you how special you are. May this new chapter bring you peaceful moments, unforgettable memories, big dreams coming true, and plenty of reasons to laugh.\n\nKeep shining, keep smiling, and never forget that you deserve a beautiful year ahead. ❤️`;let typed=false;function typeLetter(){if(typed)return;typed=true;const el=$('#typewriter');let i=0;function step(){if(i<letter.length){el.innerHTML+=letter[i]==='\n'?'<br>':letter[i];i++;setTimeout(step,25);}}step();}
$('#finalBtn').onclick=()=>{show('finale');launchConfetti();};$('#replayBtn').onclick=()=>{typed=false;$('#typewriter').innerHTML='';show('hero');};
function toast(t){const el=$('#toast');el.textContent=t;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2200);}
function makeCard(){const c=$('#cardCanvas'),ctx=c.getContext('2d');const g=ctx.createLinearGradient(0,0,1080,1350);g.addColorStop(0,'#171020');g.addColorStop(1,'#6d3455');ctx.fillStyle=g;ctx.fillRect(0,0,1080,1350);ctx.fillStyle='rgba(255,255,255,.08)';for(let i=0;i<70;i++){ctx.beginPath();ctx.arc(Math.random()*1080,Math.random()*1350,Math.random()*3+1,0,Math.PI*2);ctx.fill();}ctx.textAlign='center';ctx.fillStyle='#ff9bb3';ctx.font='600 32px Arial';ctx.fillText('A LITTLE BIRTHDAY SURPRISE',540,300);ctx.fillStyle='#fff';ctx.font='700 92px Georgia';ctx.fillText('HAPPY',540,470);ctx.fillStyle='#ff9bb3';ctx.fillText('BIRTHDAY!',540,575);ctx.fillStyle='#eee';ctx.font='30px Arial';ctx.fillText('May your new chapter be full of',540,720);ctx.fillText('beautiful memories & reasons to smile.',540,765);ctx.font='64px Arial';ctx.fillText('🎂  ❤️  ✨',540,930);ctx.fillStyle='#bbb';ctx.font='24px Arial';ctx.fillText('2 June',540,1120);ctx.fillStyle='#fff';ctx.font='24px Arial';ctx.fillText('Made with love ✦',540,1190);return c;}
$('#downloadBtn').onclick=()=>{const c=makeCard();const a=document.createElement('a');a.download='birthday-card.png';a.href=c.toDataURL('image/png');a.click();toast('📥 Birthday card downloaded!');};
$('#shareBtn').onclick=async()=>{try{const c=makeCard();const blob=await new Promise(r=>c.toBlob(r,'image/png'));const file=new File([blob],'birthday-card.png',{type:'image/png'});if(navigator.share&&navigator.canShare?.({files:[file]})){await navigator.share({title:'Happy Birthday ❤️',text:'A little birthday surprise!',files:[file]});}else if(navigator.share){await navigator.share({title:'Happy Birthday ❤️',text:'A little birthday surprise!',url:location.href});}else{await navigator.clipboard.writeText(location.href);toast('🔗 Link copied to clipboard!');}}catch(e){if(e.name!=='AbortError')toast('Could not open sharing.');}};
function launchConfetti(){for(let i=0;i<28;i++){const x=document.createElement('span');x.textContent=['🎉','✨','❤️','🎈'][i%4];x.style.position='fixed';x.style.zIndex=40;x.style.left=Math.random()*100+'vw';x.style.top='55vh';x.style.fontSize=20+Math.random()*20+'px';x.style.pointerEvents='none';x.style.transition='transform 1.7s ease,opacity 1.7s';document.body.appendChild(x);requestAnimationFrame(()=>{x.style.transform=`translate(${(Math.random()-.5)*180}px,${-250-Math.random()*350}px) rotate(${Math.random()*360}deg)`;x.style.opacity=0;});setTimeout(()=>x.remove(),1800);}}
